// Auto-generated by scrape.py — do not edit manually
const ITEMS = [
  {
    "title": "Sleeve Classic: EURO – 59x92mm",
    "asin": "B0BRNR7GS2",
    "image": "https://m.media-amazon.com/images/I/316O8A-LD4L._SS135_.jpg",
    "price": "R$ 25,85",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BRNR7GS2/?tag=guilhermefsp-20"
  },
  {
    "title": "Sleeve Classic: MINI-EURO 44x68mm, Redbox, Plástico para Proteção de Cartas",
    "asin": "B0BRNQ9BKB",
    "image": "https://m.media-amazon.com/images/I/31CtZKIa7wL._SS135_.jpg",
    "price": "R$ 13,32",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BRNQ9BKB/?tag=guilhermefsp-20"
  },
  {
    "title": "Sleeve Cristal: EURO – 59x92mm, Redbox, Plástico para Proteção de Cartas",
    "asin": "B0BRQNZKCC",
    "image": "https://m.media-amazon.com/images/I/41bLAIlIAVL._SS135_.jpg",
    "price": "R$ 12,00",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BRQNZKCC/?tag=guilhermefsp-20"
  },
  {
    "title": "Sleeve Classic: GOLD – 80x120mm",
    "asin": "B0BRNR23LR",
    "image": "https://m.media-amazon.com/images/I/31fqZClbBbL._SS135_.jpg",
    "price": "R$ 13,22",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BRNR23LR/?tag=guilhermefsp-20"
  },
  {
    "title": "Sleeve Classic: STANDARD 63,5x88mm, PADRÃO, Redbox, TCG, Plástico para Proteção de Cartas",
    "asin": "B0BRNMHJCW",
    "image": "https://m.media-amazon.com/images/I/31wVwz1nOSL._SS135_.jpg",
    "price": "R$ 12,98",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BRNMHJCW/?tag=guilhermefsp-20"
  },
  {
    "title": "NOVIIML le Card Game - Create an Ecological Paradise in the Heart of the Forest! Clever Strategy Game, Family Game for Kids & Adults, Ages 10+, 2-5 Players, 60 Min Playtime, Made by Lookout Games",
    "asin": "B0C87WK67Z",
    "image": "https://m.media-amazon.com/images/I/51C-pZGxcBL._SS135_.jpg",
    "price": "R$ 250,05",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0C87WK67Z/?tag=guilhermefsp-20"
  },
  {
    "title": "R&R Games: Amalfi Renaissance - Ship & Lighthouse Placement Game, Navigate, Discover & Aquire, Ages 14+, 1-4 Players, 90-120 Min",
    "asin": "B0CMJB52D6",
    "image": "https://m.media-amazon.com/images/I/41ZSgj27lyL._SS135_.jpg",
    "price": "R$ 524,55",
    "category": "Outros",
    "affiliate_url": "https://www.amazon.com.br/dp/B0CMJB52D6/?tag=guilhermefsp-20"
  },
  {
    "title": "SETI: Busca por inteligência extraterrestre",
    "asin": "B0CZBCRC3S",
    "image": "https://m.media-amazon.com/images/I/51vlIDfm7+L._SS135_.jpg",
    "price": "",
    "category": "Outros",
    "affiliate_url": "https://www.amazon.com.br/dp/B0CZBCRC3S/?tag=guilhermefsp-20"
  },
  {
    "title": "Arcs Board Game by Leder Games | Ages 14+ | 2–4 Players | Tactical Space Opera Strategy Game with Trick-Taking Action System, Galactic Warfare, Diplomacy & Asymmetric Play",
    "asin": "B0D856FJ1J",
    "image": "https://m.media-amazon.com/images/I/51aE-pv9qWL._SS135_.jpg",
    "price": "R$ 447,11",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0D856FJ1J/?tag=guilhermefsp-20"
  },
  {
    "title": "AEG Ready Set Bet | Head Off to The Races | Betting & Bluffing | Real-Time Dice Rolling Party Game | Simultaneous Play | 2-6 Players | Ages 10+",
    "asin": "B09YBXXVLQ",
    "image": "https://m.media-amazon.com/images/I/51i-0stnNNL._SS135_.jpg",
    "price": "R$ 357,29",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B09YBXXVLQ/?tag=guilhermefsp-20"
  },
  {
    "title": "Smart Plug Max Wi-Fi Positivo Casa Inteligente, 16A, NBR 14136, Configuração Rápida, 1600W Bivolt – Compatível com Alexa",
    "asin": "B0BNSVWWDR",
    "image": "https://m.media-amazon.com/images/I/41+kfD6uGhL._SS135_.jpg",
    "price": "R$ 89,00",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BNSVWWDR/?tag=guilhermefsp-20"
  },
  {
    "title": "Tomada De Parede Duo Com 2 Entradas Usb Bivolt Jwcom (Branco)",
    "asin": "B0B23B7ZCF",
    "image": "https://m.media-amazon.com/images/I/31zzrMcg4uL._SS135_.jpg",
    "price": "R$ 37,80",
    "category": "Outros",
    "affiliate_url": "https://www.amazon.com.br/dp/B0B23B7ZCF/?tag=guilhermefsp-20"
  },
  {
    "title": "Colchão Queen Emma Duo Comfort - 158x198x18 cm, Conforto de Dupla Face, Suporte ideal para o corpo, Alta Durabilidade, Capa Lavável, 100 Noites de Teste, 10 anos de garantia",
    "asin": "B08YKC39Y7",
    "image": "https://m.media-amazon.com/images/I/31JFJTCSdlL._SS135_.jpg",
    "price": "R$ 1.689,00",
    "category": "Outros",
    "affiliate_url": "https://www.amazon.com.br/dp/B08YKC39Y7/?tag=guilhermefsp-20"
  },
  {
    "title": "Creality Sistema De Filamento Automático Para Impressora 3D Multicolorida Cfs Oficial, Armazenamento De Filamento À Prova De Umidade, Suporta 4 Dispositivos Paralelos Para Impressão Em 16 Cores, Par",
    "asin": "B0DR8VCDCH",
    "image": "https://m.media-amazon.com/images/I/41biYxvinWL._SS135_.jpg",
    "price": "",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0DR8VCDCH/?tag=guilhermefsp-20"
  },
  {
    "title": "Kit 5 Lâmpadas AVANT NEO Smart LED 10W E27 Dimerizável RGB Compatível com Alexa e Google Home Controle voz Wifi Casa Inteligente Tuya",
    "asin": "B0FDLM1L2R",
    "image": "https://m.media-amazon.com/images/I/410a5td2JYL._SS135_.jpg",
    "price": "",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0FDLM1L2R/?tag=guilhermefsp-20"
  },
  {
    "title": "Luminária Inteligente 18W 3000-6500K Wifi Elgin Quadrada de Embutir compatível com Alexa e Google Home",
    "asin": "B08TQGGTCC",
    "image": "https://m.media-amazon.com/images/I/31DeXLj-wuL._SS135_.jpg",
    "price": "R$ 99,34",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B08TQGGTCC/?tag=guilhermefsp-20"
  },
  {
    "title": "THIRDREALITY Pacote com 4 luzes noturnas multifuncionais, repetidor Zigbee, 3 em 1 combina um sensor de movimento, um sensor de iluminação e luz noturna colorida RGB, brilho 1-100% ajustável, hub",
    "asin": "B0CX1G833P",
    "image": "https://m.media-amazon.com/images/I/31LjtH2-qBL._SS135_.jpg",
    "price": "R$ 944,61",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0CX1G833P/?tag=guilhermefsp-20"
  },
  {
    "title": "LED Night Light Upgrade,[6 Pack] Plug-in,Super Smart Dusk to Dawn Sensor, Cool White ,Night Lights Suitable BedroomHallway,Kids,Garage,Compact Nightlight",
    "asin": "B09BJLFRYR",
    "image": "https://m.media-amazon.com/images/I/31ajZw+MP6L._SS135_.jpg",
    "price": "",
    "category": "Olívia",
    "affiliate_url": "https://www.amazon.com.br/dp/B09BJLFRYR/?tag=guilhermefsp-20"
  },
  {
    "title": "Refletor LED Inteligente 50W Elgin RGB Smart Wifi compatível com Alexa e Google Home",
    "asin": "B09QCW73S5",
    "image": "https://m.media-amazon.com/images/I/31jcAaNKOqL._SS135_.jpg",
    "price": "R$ 279,90",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B09QCW73S5/?tag=guilhermefsp-20"
  },
  {
    "title": "Creality Kit de acessórios de atualização CFS oficial da série K1, atualize para impressão multicolorida conectando o sistema de filamento CFS, compatível com impressora 3D K1 Max, K1C, K1, K1 SE",
    "asin": "B0F13NWL4C",
    "image": "https://m.media-amazon.com/images/I/41iRqeEip+L._SS135_.jpg",
    "price": "R$ 667,18",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0F13NWL4C/?tag=guilhermefsp-20"
  },
  {
    "title": "Kit de acessórios de atualização CFS oficial da série K1 da Creality, permite impressão 3D multicolorida com sistema de filamento CFS, compatível com impressoras 3D K1 Max, K1C, K1, K1 SE",
    "asin": "B0F7Y45353",
    "image": "https://m.media-amazon.com/images/I/41DUPb9RlgL._SS135_.jpg",
    "price": "R$ 397,17",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0F7Y45353/?tag=guilhermefsp-20"
  },
  {
    "title": "Puff Vira Cama Casal Para Descanso - Diversas Cores (Bege)",
    "asin": "B0DR9H2CXP",
    "image": "https://m.media-amazon.com/images/I/41hZzvEz5OL._SS135_.jpg",
    "price": "R$ 674,78",
    "category": "Outros",
    "affiliate_url": "https://www.amazon.com.br/dp/B0DR9H2CXP/?tag=guilhermefsp-20"
  },
  {
    "title": "CMON Marvel United Enter The Spider-Verse Expansion | Tabletop Miniatures Game | Strategy Game | Cooperative Game for Adults and Kids | Ages 14+ | 1-4 Players | Avg. Playtime 40 Minutes | Made by CMON",
    "asin": "B0BNLN6791",
    "image": "https://m.media-amazon.com/images/I/51aCUOIVWhL._SS135_.jpg",
    "price": "R$ 268,28",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BNLN6791/?tag=guilhermefsp-20"
  },
  {
    "title": "Azul - Jogo de Tabuleiro para 6 Jogadores a Partir de 8 Anos",
    "asin": "B077MZ2MPW",
    "image": "https://m.media-amazon.com/images/I/61N5Hys8OaS._SS135_.jpg",
    "price": "R$ 371,16",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B077MZ2MPW/?tag=guilhermefsp-20"
  },
  {
    "title": "AEG Let's Go! to Japan - Strategy Card Game, Plan & Experience Your Dream Vacation, Storytelling & Travel Game, Solo Or Comp, Ages 10+, 1-4 Players",
    "asin": "B0CZBCPF53",
    "image": "https://m.media-amazon.com/images/I/51K53+opuoL._SS135_.jpg",
    "price": "",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0CZBCPF53/?tag=guilhermefsp-20"
  },
  {
    "title": "MeepleBR, Expansão Terraforming Mars: Prelúdio, jogo de tabuleiro expert, 1 a 5 jogadores",
    "asin": "B07F4J9MFZ",
    "image": "https://m.media-amazon.com/images/I/51C9nWItN3L._SS135_.jpg",
    "price": "R$ 149,90",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B07F4J9MFZ/?tag=guilhermefsp-20"
  },
  {
    "title": "Galápagos, SCOUT, Jogo de Cartas, 14 anos, 2 a 5 jogadores, 20min",
    "asin": "B0D54PNXRN",
    "image": "https://m.media-amazon.com/images/I/41Ui12rdd3L._SS135_.jpg",
    "price": "R$ 146,91",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0D54PNXRN/?tag=guilhermefsp-20"
  },
  {
    "title": "Restoration Games Thunder Road Carnival Of Chaos - Expansão de Jogo - Adulto - Não Foldável",
    "asin": "B0DKPF8LSF",
    "image": "https://m.media-amazon.com/images/I/413NrE34uOL._SS135_.jpg",
    "price": "R$ 573,04",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B0DKPF8LSF/?tag=guilhermefsp-20"
  },
  {
    "title": "Wyrd Games Presents Vagrantsong - A Bone -Chillingly Spooky Adventure Board Games",
    "asin": "B09T5JC5Z1",
    "image": "https://m.media-amazon.com/images/I/513jyUOGHcL._SS135_.jpg",
    "price": "R$ 572,36",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B09T5JC5Z1/?tag=guilhermefsp-20"
  },
  {
    "title": "Torre De Aprendizagem Montessori Madeira Mesa Baleia Segura",
    "asin": "B0D6BY5JMP",
    "image": "https://m.media-amazon.com/images/I/31uqwlSpLoL._SS135_.jpg",
    "price": "R$ 309,90",
    "category": "Casa",
    "affiliate_url": "https://www.amazon.com.br/dp/B0D6BY5JMP/?tag=guilhermefsp-20"
  },
  {
    "title": "Ferramentas Madeira Construção Kits Infantil Montessori Brinquedos",
    "asin": "B0DJ57N1WS",
    "image": "https://m.media-amazon.com/images/I/41hVx1+osML._SS135_.jpg",
    "price": "R$ 149,00",
    "category": "Olívia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0DJ57N1WS/?tag=guilhermefsp-20"
  },
  {
    "title": "Interruptor Inteligente ZigBee 3 Botões Touch NovaDigital Branco Compatível Alexa Tuya Smart Life",
    "asin": "B0B4TYHQD5",
    "image": "https://m.media-amazon.com/images/I/21eOU5MfpNL._SS135_.jpg",
    "price": "R$ 83,90",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0B4TYHQD5/?tag=guilhermefsp-20"
  },
  {
    "title": "BTF-LIGHTING RGBCCT 5 cores em 1 fita de LED 5050SMD RGBWW RGB + temperatura de cor regulável 2700K-6500K 5 metros 60 pixel/m 300LED IP30 DC24V PCB branco para decoração de casa (sem adaptador ou",
    "asin": "B0BBGGRGDL",
    "image": "https://m.media-amazon.com/images/I/41xp45jEKbL._SS135_.jpg",
    "price": "R$ 223,75",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BBGGRGDL/?tag=guilhermefsp-20"
  },
  {
    "title": "Kit Roteador Mesh AC1900 TP-Link Deco S7(3-pack), Dual Band 2.4/5 GHz, Conecte até 100+ Dispositivos, Cobertura de até 520M2, 3 Portas Gigabit Ethernet, Funciona com Amazon Alexa, Controle dos Pais",
    "asin": "B0BBV29JXX",
    "image": "https://m.media-amazon.com/images/I/31XSDfBmcUL._SS135_.jpg",
    "price": "R$ 1.015,99",
    "category": "Tecnologia",
    "affiliate_url": "https://www.amazon.com.br/dp/B0BBV29JXX/?tag=guilhermefsp-20"
  },
  {
    "title": "Greater Than Games Spirit Island Ace Studios Multicor, Jogo de Tabuleiro, 3+ anos, 4 Jogadores, Fantasia / Ambiental / Mitologia",
    "asin": "B01MUHP51S",
    "image": "https://m.media-amazon.com/images/I/41LldcC1tiL._SS135_.jpg",
    "price": "R$ 651,51",
    "category": "Jogos e Acessórios",
    "affiliate_url": "https://www.amazon.com.br/dp/B01MUHP51S/?tag=guilhermefsp-20"
  },
  {
    "title": "LEGO® Creator 3 em 1 – Dragão Vermelho Criaturas Mitológicas Seres Místicos 31145",
    "asin": "B0CGY9Q4ZW",
    "image": "https://m.media-amazon.com/images/I/41iv003et9L._SS135_.jpg",
    "price": "R$ 89,98",
    "category": "Outros",
    "affiliate_url": "https://www.amazon.com.br/dp/B0CGY9Q4ZW/?tag=guilhermefsp-20"
  }
];
